version: "3.8"

services:

  configserver:
    image: njoyer/configserver:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8071:8071"
    networks:
      - njoyerbank

  accounts:
    image: njoyer/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - njoyerbank
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: njoyer/loans:latest
    ports:
      - "8090:8090"
    networks:
      - njoyerbank
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: njoyer/cards:latest
    ports:
      - "9000:9000"
    networks:
      - njoyerbank
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  njoyerbank: